name: Example Config
version: 1.0.0
schema: v1

models:
  - name: DeepSeek Local
    provider: openai
    model: deepseek-coder-v2-lite-instruct
    apiBase: https://unelastically-generative-owen.ngrok-free.dev/v1
    apiKey: sk-local
    defaultCompletionOptions:
      contextLength: 9000
    roles:
      - chat
      - edit

mcpServers: []